[lightning]
    seed=20090220
    epochs=20
    batch_size=128
    dataloader_workers=12
    persistent_workers=true
    grad_acc=4
    devices=4
    precision="16-mixed"
    grad_clip=3.0
    grad_ckpt=true

    [lightning.imggencallback]
        id="XUT-0.35B-Qwen3-0.6B-256px-patch2-tread"
        num=64
        preview_num=8
        batch_size=64
        steps=32
        period=512
    [lightning.logger]
        name="XUT-0.35B-Qwen3-0.6B-256px-patch2-tread"
        project="HomeDiffusion"
        offline=false


[trainer]
    name="test"
    lr=0.5 # We have muP scale, need higher LR here
    optimizer="torch.optim.AdamW"
    opt_configs = {"weight_decay"= 0.02, "betas"= [0.9, 0.98]}
    lr_sch_configs = {"end"= -1, "mode"= "cosine", "warmup"= 1000, "min_value"= 0.01}
    te_use_normed_ctx=false


[dataset]
    [[dataset.datasets]]
        class = "hdm.data.danbooru512.Danbooru512Dataset"
        [dataset.datasets.kwargs]
            dataset_folder = "/mnt/mp44l/nn/datasets/danbooru-512"
            load_meta=false


[model]
    config="./config/model/xut-qwen3-sm-tread.yaml"
    inference_dtype = "torch.float16"
